org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.2.19

mod_id=nestworld_teams
mod_version=1.0.0
mod_group=com.skyblock.dynamic.teams

ftb_library_version=2001.2.9
ftb_teams_version=2001.3.2
ftb_chunks_version=2001.3.8
architectury_version=9.1.12
