    buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:6.0.24'
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'idea'

group = 'net.market.realmarket'
version = '1.0'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    copyIdeResources = true
    runs {
        client {
                workingDirectory project.file('run')
                property 'forge.logging.markers', 'REGISTRIES'
                args '--username', 'Chaos1924'
                mods { create("realmarket") { source sourceSets.main } }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            mods { create("realmarket") { source sourceSets.main } }
        }
    }
}

repositories {
    maven { url = "https://cursemaven.com" }

    // Резолвим Forge і API (автоматично додається, але можна явно вказати)
    maven {
        name "Modmaven"
        url "https://modmaven.dev/"
        // For Gradle 5.1 and above, limit it to just AE2
        content {
            includeGroup 'appeng'
        }
    }    

    flatDir { dirs 'libs' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.3.22'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'org.java-websocket:Java-WebSocket:1.5.3'

   implementation fg.deobf("curse.maven:applied-energistics-2-223794:7148487")
   implementation fg.deobf("curse.maven:guideme-1173950:6489464")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}