
#General settings
[general]
	#The host of the database
	host = "109.207.193.71"
	#database port
	#Range: 0 ~ 65535
	db_port = 3306
	#whether use SSL
	use_ssl = false
	#username
	user_name = "player_inventory"
	#password
	password = "gd7)FmOQ564RMX17"
	#database name
	db_name = "player_inventory"
	#the server id should be unique
	Server_id = {{SERVER_ID}}
	#The worlds that will be synchronized. If running on a server, leave array empty.
	sync_world = []
	#Whether to sync advancements between servers
	sync_advancements = true
	#Whether synchronize chat
	sync_chat = true
	#Whether recieve messages from other servers as host
	IsChatServer = true
	ChatServerIP = "localhost"
	#Range: 0 ~ 65535
	ChatServerPort = 7900
	#Use the old (pre-Base64) serialization format for writing data to the database.
	#Set to true ONLY if you have older mod versions reading the same database.
	#This only affects writing data, the mod can read both Base64 and pre-Base64 serialization.
	#New installations should leave this as 'false'.
	use_legacy_serialization = false
	#Override the title of placeholder items which are unavailable on the current server.
	item_placeholder_title_override = ""
	#Override the description of placeholder items which are unavailable on the current server.
	item_placeholder_description_override = ""

